public enum GameState
{
    GAMECONTROLLER_STARTING = -1,   //just for debug
    
    ROS_CONNECTION = 0,
    ROS_HELLO_WORLD_ACK = 900,

    STARTED = 1,
    NEW_PROFILE_PROMPT = 2,
    MUST_LOGIN_PROMPT = 3,
    ENTER_NAME_PROMPT = 4,
    EVALUATING_TYPED_NAME = 5,
    LISTING_IMAGES = 6,
    TAKING_WEBCAM_PIC = 7,
    CHECKING_TAKEN_PIC = 8,
    PIC_APPROVAL = 9,
    PIC_DISAPPROVAL = 10,
    SAVING_PIC = 11,
    LISTING_PROFILES = 12,
    LOGIN_DOUBLE_CHECK = 13,
    LOGGING_IN = 14,
    CANCELLING_LOGIN = 15,
    WELCOME_SCREEN = 16,
    SHOWING_SELECTED_PHOTO = 17,
    DELETING_PHOTO = 18,

    API_ERROR_CREATE = 90,
    API_ERROR_COUNTING_FACES = 91,
    API_ERROR_ADDING_FACE = 92,
    API_ERROR_IDENTIFYING = 93,
    API_ERROR_GET_NAME = 94,
    API_ERROR_TRAINING_STATUS = 95,
    API_ERROR_DELETING_FACE = 96
}